" Vundle
filetype off
set rtp+=~/.vim/vundle/
call vundle#rc()
Bundle 'Shougo/neocomplcache'
Bundle 'speeddating.vim'
Bundle 'DirDiff.vim'
Bundle 'autodate.vim'
Bundle 'project.tar.gz'
Bundle 'sudo.vim'
filetype on
